### ISSUE TITLE
Drawing/Displaying a radius

### ISSUE THREAD

**Issue by movostudios** [GuillaumeLeclerc/vue-google-maps#1]
HI ya,

Thanks for putting this project together. Its a really nice bit of work.

I am needing to add a radius/circle from a central point and get the bounds based on that. Its basically for a project where users enter the distance they are willing to travel.

Going through the code, this currently isn't available. Are you either planning it soon or are you have for pull requests?

Cheers. Keep up the good work.

**Comment by GuillaumeLeclerc** [comment]
Hello,

Thank you for your interest. The list of implemented components are available on the wiki.

Indeed, circles are not implemented yet. But it should not take a lot of time. I'm a little busy this week.

You can either ping me next week or make a pull request.

**Comment by GuillaumeLeclerc** [comment]
I took a look at [the documentation](https://developers.google.com/maps/documentation/javascript/3.exp/reference#Circle). And It should be pretty straight forward. The implementation will look like the one for Polygons and can be done using the `utils` already present in the repo.

I'll try to do it as soon as I finish my urgent work. But feel free to contribute if really need it quickly.

**Comment by movostudios** [comment]
Thanks @GuillaumeLeclerc I've posted a PR: https://github.com/GuillaumeLeclerc/vue-google-maps/pull/2

Cheers.
