### ISSUE TITLE
Issue with Cluster and Markers update

### ISSUE THREAD

**Issue by smartpierre** [GuillaumeLeclerc/vue-google-maps#10]
Hi !

So I have a map with markers on it. I can paginate through the markers and they are added/removed from the map.
It works perfectly until I tried to add the cluster...

It looks like there's something wrong on the update of the markers, the Google Maps SDK is throwing this error : 

![screenshot from 2016-01-21 14 21 51](https://cloud.githubusercontent.com/assets/8858750/12481609/9b243410-c04a-11e5-8111-493f1d6df04e.png)

Here is the interesting part of the code of my vue file : 

https://gist.github.com/smartpierre/b69426dcd9098c803ab3

In setMarkers, I compare the old markers with the new ones, I remove the old markers that are not in the new list and add the new that are missing (so it does not make all the markers DROP each time I refresh the map)

If you have any idea, I'll take it. Maybe I'm doing something wrong ? In the meantime I'll do without the cluster :D

**Comment by GuillaumeLeclerc** [comment]
Sadly there is nothing I can do as it is a bug of the cluster. Do you really want me to implement the quickfix ? I think it is better if you do it in your npm package descriptor.

In general I don't think it is a great idea to make a release for hotfix and then revert it two days later because the underlying bug has been fixed.

I'm really sorry about the two bugs on `vue-google-maps` but we need the other libraries to get fixed.

**Comment by smartpierre** [comment]
Oh so it's again a problem with vue-router ?? Damn !!!

Well I can live without cluster for now, don't worry about making a hotfix !

Thank you Guillaume :)

**Comment by GuillaumeLeclerc** [comment]
No it's in the clustering library itself. There is a pull request pending. But the owner has not merged it yet :/

**Comment by GuillaumeLeclerc** [comment]
The PR is here: googlemaps/js-marker-clusterer#39

**Comment by smartpierre** [comment]
Oh ok ! Well, hopefully that will be merged soon :)

**Comment by GuillaumeLeclerc** [comment]
I think so, don't need to worry. I expect you don't have a deadline soon.

**Comment by GuillaumeLeclerc** [comment]
The PR has been merged, can you confirm it works ?

**Comment by smartpierre** [comment]
It is not merged yet https://github.com/googlemaps/js-marker-clusterer/pull/39

**Comment by smartpierre** [comment]
Although this fix has been applied https://github.com/googlemaps/js-marker-clusterer/pull/41/commits
I'll check today if it fix everything.

**Comment by smartpierre** [comment]
Just tested, I do not have any errors, however it does not show any cluster :/

**Comment by GuillaumeLeclerc** [comment]
Maybe you can open a new issue since it must be a different problem

**Comment by smartpierre** [comment]
Sorry I'm an idiot, it's totally working, I forgot to run webpack...

**Comment by GuillaumeLeclerc** [comment]
No problem
