### ISSUE TITLE
Lodash dependency

### ISSUE THREAD

**Issue by koluch** [GuillaumeLeclerc/vue-google-maps#100]
Hi,

You have a dependency to 'lodash' library version ^3.10.1, while current version is 4.15.0. Furthermore, you put it in 'peerDependencies' (why?), so now it's impossible to use your module in a project, which have a dependency to 'lodash' version 4.*.

Could you please move this dependency to 'dependencies', or update the version?

**Comment by GuillaumeLeclerc** [comment]
I think the main reason it's in the peer dependencies is, depending on which version you use you actually don't need lodash since it might be embedded inside. I will update the version.

**Comment by koluch** [comment]
Thank!
