### ISSUE TITLE
`loaded` promise resolves without map instance

### ISSUE THREAD

**Issue by PandaWhisperer** [GuillaumeLeclerc/vue-google-maps#101]
## Synopsis

The `loaded` promise  does **not** resolve with the `map` instance, as [described here][1]. Instead, it resolves to `undefined` (see [manager.js#L10-L12][2]). 

[1]: https://github.com/GuillaumeLeclerc/vue-google-maps/wiki/loaded
[2]: https://github.com/GuillaumeLeclerc/vue-google-maps/blob/master/src/manager.js#L10-L12

## Background

I am trying to implement Place Search, which requires instantiating `google.maps.places.PlacesService`, which needs an instance of the map object. I currently can't seem to find another way to get a hold of it (other than the `loaded` promise).

**Comment by PandaWhisperer** [comment]
**Update:** I was able to achieve what I wanted by using the Map component's [`mapCreated` promise][1]. 

Additionally, it turns out that the [`mapObject` is also exposed][2] on the component. 

Anyhow, the documentation for the `loaded` promise is still incorrect, as mentioned in the original issue.

[1]: https://github.com/GuillaumeLeclerc/vue-google-maps/blob/master/src/components/map.vue#L125
[2]: https://github.com/GuillaumeLeclerc/vue-google-maps/wiki/Map#javascript-object-properties

**Comment by GuillaumeLeclerc** [comment]
Indeed you are right and it is impossible to resolve it to a map since there might not be a map (you could load the library without instantiating a single map, just to use the autocomplete form). Or you could have multiple maps on the page. Therefore the doc is wrong, I will update that now.

**Comment by GuillaumeLeclerc** [comment]
Actually it was a typo in the code, the text description is absolutely correct
