### ISSUE TITLE
About events

### ISSUE THREAD

**Issue by smartpierre** [GuillaumeLeclerc/vue-google-maps#11]
Hi !

Is it possible to have an example about how to use events ?

I tried many things but never managed to get them working.

Here is a simple test: 

https://gist.github.com/smartpierre/813149ffb0a302d9d71f

When I drag the marker and drop it on the map, the event 'g-dragend' is not triggered

**Comment by GuillaumeLeclerc** [comment]
I will take a look but there is an example of g-click and g-dblclick in the example project. 

I will add drag to the example too and fix any bug I find.

**Comment by smartpierre** [comment]
I do not see anything here related to events : 

https://github.com/GuillaumeLeclerc/vue-google-maps-example/blob/master/src/app.vue

Or is it the wrong file ?

**Comment by GuillaumeLeclerc** [comment]
It is the correct file.

I think you are not just very used to vue events yet. And sorry for not looking at your gist before. I'll try to explain your mistake. 

You added the hook on your component. That means you are catching events reaching your component : This is the 3 different cases that can happen.

- A parent of your component broadcasted an event
- A child of your component is dispatching an event
- An `$emit` is called on your component.

(You can find more information about the differences between `$dispatch`, `$broadcast`, and `$emit` [here](http://vuejs.org/guide/components.html#Custom_Events)

In `vue-google-map`, I decided that the map components would not be dispatching any events. If they were doing so all non-catched events (and believe me there are a lot of them) would trigger up until the root of the shadow DOM. Example. If there is a click on a marker. The click will be triggered on the cluster, then on the map object then on the containing object, then on the parent, ... until we reach the `$root` component. As there are a lot of events it was not a good decision.

I decided that events would be only triggered on the marker itself, it also helps you finding on which object the event is happening. If you want to listen a `g-draggend` you need to add it on the marker itself not your component. Here is a simple example:

```html
<marker @g-dragend="myMethod" ...></marker>
<marker ..></marker> <!-- Here you don't listen for event on this marker -->
```

```javascript
export default {
  ...
  methods: {
    myMethod () {
      // do your stuff
    }
  }
  ...
}
```
Please note you can also pass events to the event hook. example:

```html
<marker v-for="m in markers" @g-dragend="myMethod(m)"></marker>
```

More examples [here](http://vuejs.org/guide/events.html#Inline_Statement_Handler)

I added an example here GuillaumeLeclerc/vue-google-maps-example@e0727ed5ab93d797752711e00d3f00ff3160c5fb

**Comment by smartpierre** [comment]
You are awesome, I didn't knew that you could catch event on components like that !

It's clear like water now :)

Now that you explain it, it is indeed better that event are not propagated to parent in this multi-layer scheme.

I've been playing on Vue.js for 2 weeks now I'm still learning ^^

Thank you Guillaume !

**Comment by GuillaumeLeclerc** [comment]
Glad I helped you :)
