### ISSUE TITLE
Getting the map object

### ISSUE THREAD

**Issue by ethanclevenger91** [GuillaumeLeclerc/vue-google-maps#111]
Hey, trying to get the map object to render some directions and some other stuff that either isn't in this library or isn't documented. The documentation says to use `vm.mapObject`, but what is `vm` referring to in that context?

Right now I've got a component with a `<map v-ref:map></map>` as a child component, but `this.$refs.map.mapObject` is undefined:

``` js
import { Map, Marker, Cluster, loaded } from 'vue-google-maps'
...
ready() {
    var vm = this;
    loaded.then(function() {
      vm.directionsDisplay = new google.maps.DirectionsRenderer();
      console.log(vm.$refs.map.mapObject);
    });
  }
```

**Comment by xkjyeah** [comment]
Your code is correct. But mapObject is not available at that point because the Map instance hasn't called new google.maps.Map(...).

You need to wait on `map.mapCreated` promise.

**Comment by ethanclevenger91** [comment]
That worked, thanks a lot. Is that promise documented?

**Comment by xkjyeah** [comment]
I wasn't one minute ago...

I'm not too sure about whether it should be part of the API, but I'll just document it anyway since we're not at v1.0.0 yet.
