### ISSUE TITLE
Bind InfoWindow to marker

### ISSUE THREAD

**Issue by schmidex** [GuillaumeLeclerc/vue-google-maps#12]
currently infoWindows inside Markers are bound to the map with an absolute position resulting in an ugly overlay.
It would be nive if infoWindows inside markers could be bound to the marker with
infowindow.open(map, marker);
This way the window would be automatically positioned on top of the marker.

Thanks for your work..

**Comment by GuillaumeLeclerc** [comment]
That's actually a great idea. I'll try to implement it today. If you prefer you can do it yourself as it is your idea, I always accept pull requests :)

**Comment by GuillaumeLeclerc** [comment]
It was implemented in v0.1.2. Hope it is what you expect.

**Comment by smartpierre** [comment]
Is that part of the feature ? :P

https://github.com/GuillaumeLeclerc/vue-google-maps/blob/fe7806b17c66af331192076b45aefda3b4d493fe/src/components/infoWindow.vue#L5

**Comment by GuillaumeLeclerc** [comment]
Sorry I got angry because of somthing not woking. 

Good catch ;)

**Comment by GuillaumeLeclerc** [comment]
@schmidex It was a great idea. We are saving a `$watch` operation on each marker and the maps are more readable.

You can see how it look on the example project. I updated it to `v0.1.2`
