### ISSUE TITLE
How to add a name attribute to placeInput?

### ISSUE THREAD

**Issue by connor11528** [GuillaumeLeclerc/vue-google-maps#122]
I have a placeInput in a form. I need to submit the location to my server. In order to grab the value I need to add a name attribute on the input bar. What is the best way to add a name attribute and submit placeInput data to the server?

Thank you

**Comment by JoshuaDoshua** [comment]
@connor11528 

I would think the best way is to handle the submission with $http.post and just use the data inside the placeInput's parent component.

**Comment by connor11528** [comment]
Yeah I was looking to do it synchronously but I think ajax request will be way to go. Thank you
