### ISSUE TITLE
Issue with place_changed on PlaceInput

### ISSUE THREAD

**Issue by smartpierre** [GuillaumeLeclerc/vue-google-maps#15]
Hi Guillaume,

first of all, thank you for this new component, I see it's brand new and already working pretty well.

Here is the thing : 
I have a PlaceInput in my form, and the user whatever location he wants, to do so I have to initialize my place to an empty object.
When a place is selected on the input, I listen to the event g-place_changed and I noticed that the place is still empty, I was not filled with the information : 
I saw that in your code, you listen for the same event to update the place property, and I was thinking that maybe I catch the events at the same time at the component, but I guess that autoCompleter.getPlace() takes too much time to return the informations to the component.

Here is my code :

https://gist.github.com/smartpierre/2739399e0f2a33697cfa

It always returns : 

![screenshot from 2016-02-12 18 02 28](https://cloud.githubusercontent.com/assets/8858750/13014167/d3f6070e-d1b2-11e5-9c74-19c94abfaa42.png)

Best regards, Pierre.

**Comment by GuillaumeLeclerc** [comment]
You shouldn't be using this event (it should be private but there are no way to make event private in vue). Sorry I didn't have the time to add the documentation for this component. You should watch the props `place` instead (it is two bounded and updated as soon as the user choose a new place)

**Comment by smartpierre** [comment]
Oh okay, I will try that way :)

**Comment by GuillaumeLeclerc** [comment]
Did it worked ?

**Comment by smartpierre** [comment]
Yes, I'm watching the place variable and it's working fine :)

**Comment by mateusjatenee** [comment]
@smartpierre hi Pierre, would you mind showing us how you did it?

**Comment by smartpierre** [comment]
That should work 

https://gist.github.com/smartpierre/1344e3701326910b0dd3ee81cd5ab205
