### ISSUE TITLE
No Polygon component

### ISSUE THREAD

**Issue by Bre77** [GuillaumeLeclerc/vue-google-maps#17]
This is really a feature request. The Polyline is great, but I would really like to be able to use the Polygon type too. It seems like the Polygon and Polyline are very similar, so hopefully this is just a copy of the Polyline component with a few objects renamed.

https://developers.google.com/maps/documentation/javascript/shapes#polygons

**Comment by GuillaumeLeclerc** [comment]
I will try to do it as soon as possible. But if you have free time and feel adventurous you can make a pull request. I'd be glad to review it and merge it :)

**Comment by GuillaumeLeclerc** [comment]
I added polygons in v0.1.9. Does it work for you ?

**Comment by Bre77** [comment]
Simple polygons seem to be working perfectly! I haven't got complex polygons (ones with holes and such) working yet, but that may be an issue with my data at this stage. I will continue testing tomorrow and let you know.

**Comment by GuillaumeLeclerc** [comment]
I'll probably have some time to add complex polygons this afternoon.

**Comment by Bre77** [comment]
If you want to check my fork, I have added the 'paths' property as you suggested, but honestly I am figuring out what I am doing as I go. The issue currently is that if you have both path and paths defined, it always uses the value in paths (since it was defined last).

I appreciate you working on this, I really like your library.

**Comment by GuillaumeLeclerc** [comment]
I understand the problem I'll try to find the best possible way to do this.

**Comment by GuillaumeLeclerc** [comment]
I added paths props that support complex polygons in v0.1.10.

Can you give feedback ?

**Comment by GuillaumeLeclerc** [comment]
I assume everything is fine. Closing this issue
