### ISSUE TITLE
infowindow lost after it's closed

### ISSUE THREAD

**Issue by xkjyeah** [GuillaumeLeclerc/vue-google-maps#20]
Despite using :open.sync="...", it is not possible to reopen an InfoWindow once the "X" button is clicked. According to Google documentation, this is because the InfoWindow is removed from the map when that happens.

**Comment by GuillaumeLeclerc** [comment]
You closed the issue. Is it working for you ?

**Comment by xkjyeah** [comment]
Yep, it is. Sorry for the spam

**Comment by GuillaumeLeclerc** [comment]
No problem :)

**Comment by francisortega** [comment]
May I ask how this was solved?

**Comment by GuillaumeLeclerc** [comment]
I think you can see the vue-google-maps-example. It has an example of reopening info windows

**Comment by Profile** [comment]
example page is not working
