### ISSUE TITLE
Disable warnings for one-way bindings?

### ISSUE THREAD

**Issue by xkjyeah** [GuillaumeLeclerc/vue-google-maps#23]
Not all instances of the maps components will necessarily be used for input. They could be used purely for display e.g.

    <marker v-for="store in stores"
        :position="{lat: store.latitude, lng: store.longitude}"
    ></marker>

However, vue-google-maps will complain that `position` expects a two-way binding.

**Comment by GuillaumeLeclerc** [comment]
This is a vue warning. I know you can disable it globally. But If we add this to vue-google-maps that means no user would ever get a warning. This might not be good for some users. You can disable warnings in your project. 

If you know a way to disable them in a way that is not global please tell me and I'd be glad to implement it.
