### ISSUE TITLE
Is there a need for register-marker, register-polygon, register-polyline... etc events?

### ISSUE THREAD

**Issue by xkjyeah** [GuillaumeLeclerc/vue-google-maps#27]
I am thinking about what happens if somebody wants to write an extension to VueGoogleMaps. Since the extension will require the Map object, the register-child event should be standardized. The extension should not require vue-google-maps to support a new event named "register-some-new-extension".

P.S. IMO Angular does this rather well with dependency injection

**Comment by GuillaumeLeclerc** [comment]
First we need events to know what's the type of the first container that knows how to handle a component.

We need specific events because some parents may behave differently according to the child.

How would like the add-on interface I could try to implement it

**Comment by GuillaumeLeclerc** [comment]
Any news on this ?

**Comment by xkjyeah** [comment]
I haven't hide time to work on it recently. But I had figured that the PR
wasn't working correctly because map-ready events were bring fired in the
wrong order (child... Parent vs parent... Child).

**Comment by GuillaumeLeclerc** [comment]
No problem :) I'll let the issue open then.

**Comment by GuillaumeLeclerc** [comment]
I merged you PR
