### ISSUE TITLE
selectFirstOnEnter="true" doesn't work?

### ISSUE THREAD

**Issue by websanova** [GuillaumeLeclerc/vue-google-maps#43]
I'm trying to get the `placholder autocomplete` to fire on enter but it's not working.

It adds a "selectfirstonenter="true"` to the input's label which is a big weird. 

Also when I try clicking one of the items from the dropdown it seems like it's always giving me the last value and not the current one. I have to always do it twice to get the proper address.

It would be nice to have a fully working example for the inputs. Also I like the "Show on Map" box you have with the checkboxes in the example:

http://en.papayapods.com/?utm_source=GtHub&utm_medium=LnK&utm_campaign=V.JS%20Map%20Cmpnt.#!/search/map?city=Lausanne

Would it be possible to include a working search and show on map in the sample code on github?

**Comment by GuillaumeLeclerc** [comment]
Hello and thank you for your interest.

I agree, I will add an example of placeinput right now to the example. It's a good idea. I will try to reproduce your bug at the same time. If I can't you will just have to take a look at the example to find how use it.

The show on map is actually pretty simple (I did not do it personally, it's a coworker). we have a `mapStyle` object with some of the keys "plugged" to checkboxes using v-model. I could also add an example of that but I fear the example would become overloaded. I was planning to make a website with the docs inside and multiple examples but I don't have the time right now sorry.

**Comment by GuillaumeLeclerc** [comment]
I found the problem. The part of the code required jQuery. Which is not a dependency of `vue-google-maps`. All the websites I tested this on were already loading jQuery. This is why I could not see the bug. I hopes this fixes it for you, otherwise reopen it.

**Comment by GuillaumeLeclerc** [comment]
I also update `vue-google-maps-example` and the PlaceInput documentation. I hopes it help too
