### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by perkola** [GuillaumeLeclerc/vue-google-maps#45]
When following the example in the readme I can't get my map to load. The `map` component is resolved to a `<div class="vue-map-container">` and a `<div class="vue-map">` and the code from the Google maps API is loaded but the map never shows, only a light brown square that fills the space.

Here is my code:
```
<template>
<map
  :center="{lat:10, lng:10}"
  :map-type-id="terrain"
  :zoom="7"
></map>
</template>

<script>
import {load, Map} from 'vue-google-maps'

load('MY_KEY', '3.24');

export default {
  components: {
    Map
  }
}
</script>
```
I'm using vue-google-maps version `0.1.16` and Vue version `1.0.20`. I use Vueify with Browserify in gulp to compile `.vue` components. Any ideas what can be wrong? I suppose it has something to do with the bundling.

**Comment by GuillaumeLeclerc** [comment]
Do you have any errors ?

I tried vue `1.0.20` and everything was working fine, so I doubt the problem comes from here. 

I've nevery tried Browserify with vue. maybe another user of `vue-google-maps` might be more helpful than me.

Can you check if the resolved `<div>` does not have a width or height of `0px`.

Do you have a built version I could try to debug ?

**Comment by perkola** [comment]
@GuillaumeLeclerc 

No errors in the console or during compilation (only warning regarding the two-way binding of zoom, center and mapTypeId)

All elements related to the map has a height of `600px`.

Unfortunately  I'm not sure how to reproduce the bug in a gist or jsfiddle.

Does `vue-google-maps` require some packages to be installed like `babel` that is not specified in the `package.json`? I tried the [webpack example](https://github.com/GuillaumeLeclerc/vue-google-maps-example) and it works so it has to be a problem with `vue-google-maps` + Browserify.

**Comment by GuillaumeLeclerc** [comment]
It's very strange you don't get any errors. I can't really help you with Browserify.

There might be an error not shown because most of the code is in promises. What I advise you to do is to open the debugger and pause on caught exceptions. You might discover an error.

I hope it helps

**Comment by perkola** [comment]
When inspecting the components with VueDevTools there appears to be a `bounds` property on the Webpack example which is missing in my implementation although the component looks exactly the same.

**Comment by perkola** [comment]
That was the problem. When not passing the bounds property (which is specified as required) the map would not show. Somehow the bounds was auto computed in the Webpack example but not in my Browserify implementation. Assigning the property with bounds made it work.

**Comment by GuillaumeLeclerc** [comment]
This is very strange. So you just added a bound property to the map component right   ?

**Comment by perkola** [comment]
Yes. The Vue DevTools listed the `bounds` property as required and after passing an empty object it worked.

**Comment by GuillaumeLeclerc** [comment]
https://github.com/GuillaumeLeclerc/vue-google-maps/blob/master/src/components/map.vue#L44

shows it should not be required. Maybe it's now required by default.

**Comment by GuillaumeLeclerc** [comment]
I'm closing the issue since you made it work I'll try to keep it in mind a someone else has a similar problem

**Comment by jankincl** [comment]
Hi Perkola,

I am also using browserify in my Laravel+Vue.js project and have troubles getting the vue-google-maps to work. Would you be so kind and send an example of your gulpfile where you import the vue-google-maps or where you load the map with bounds? Would be really helpful.

Thanks!

**Comment by fundix** [comment]
same problem, after load page maps in component went to blank - only map bg and buttons
