### ISSUE TITLE
Documentation confusing

### ISSUE THREAD

**Issue by thatdoorsajar** [GuillaumeLeclerc/vue-google-maps#47]
At the bottom of the readme file "Full Documentation" is mentioned and it says to reference the wiki but there are no links to this material?! Or am I being stupid!?

**Comment by GuillaumeLeclerc** [comment]
https://github.com/GuillaumeLeclerc/vue-google-maps/wiki

You just have to click to the Wiki link on the repo page to find it

**Comment by thatdoorsajar** [comment]
Haha yeah I was just being stupid. Thanks for quick reply!
