### ISSUE TITLE
mouseover on markers doesn't work

### ISSUE THREAD

**Issue by schmidex** [GuillaumeLeclerc/vue-google-maps#5]
Looks like a typo:
mousover !== mouseover
Here: https://github.com/GuillaumeLeclerc/vue-google-maps/blob/master/src/components/marker.vue#L77

**Comment by GuillaumeLeclerc** [comment]
I feel really sorry. I planed a release tomorrow morning with a few bugfix and a new feature. 

I will include it !

Thank you !
