### ISSUE TITLE
How to close info windows when clicked on a new marker?

### ISSUE THREAD

**Issue by FWSimon** [GuillaumeLeclerc/vue-google-maps#50]
Is there any way to close all info windows so i only have the one i clicked on open?.

So if i click on a marker the info window open but close the other?

**Comment by GuillaumeLeclerc** [comment]
Yes of course. You have an opened property on infoWindows. 
You can use the g-click event on the marker. set the opened property to all infoWindows to false. and then set to true the one corresponding to the marker

**Comment by GuillaumeLeclerc** [comment]
Maybe we would like a component `<info-window-group>` that has markers as child and guarantee that there is at most one opened info windows in there. Do you think it would be a valuable addition to the library or what I told you is simple enough ?

**Comment by FWSimon** [comment]
oh, that would be nice @GuillaumeLeclerc , good idea!

I haven't tried with the g-click event yet, I'm gonna see if I can do it today 👍

**Comment by FWSimon** [comment]
@GuillaumeLeclerc So if i have this in my data function

`opened: false // Close all info windows.`

and in my method function i have this `this.opened = false;` ?
i just cant get it to work, do you have any idea?

**Comment by GuillaumeLeclerc** [comment]
Vue does not care what you have in your data object to have an impact you need to pass it to the info window using props. You can control if a infoWindow is opened by passing some variable: 

```html
<info-window :opened="your_variable"></info-window>
```

changing only your data will NEVER have any impact if the view does not read it. Other example in generic vue

```vue
<template>
  <div> Hello World </div>
</template>

<script>
export default {
  data() {
    return { visible: false}
  }
}
</script>

In this example. Changing visible to false will not hide `Hello world` unless you change it by:

`<div v-id="visible">Hello World</div>`

`opened` in vue works the same was as `v-if` does.

**Comment by FWSimon** [comment]
But if i have this `<info-window :opened.sync="false"></info-window>` and put a `v-if` on that, the status for that `v-if` would be the same for every info-windows and not just the one i clicked on.

i will try dig around, thanks :)

**Comment by GuillaumeLeclerc** [comment]
No you don't need to have a v-if. I just want to say that `opened` behaves exactly the same way as `v-if` 

what you need to do is something like this (pseudo -code)
```javascript
myHandler (clickedId) {
  //close every infoWindows.
  this.infoWindows.forEach((m) => {m.foo = false});
  //open the correct infoWindow
  this.infoWindows[clickedId].foo = true
}
```
and in your vue

`<info-window :opened="i.foo"></info-window>`

**Comment by FWSimon** [comment]
Thanks got it to work 👍  i close for now @GuillaumeLeclerc

**Comment by Rias500** [comment]
I can't seem to get this to work, the only thing that works for me at the moment is removing all the markers and adding them again to get the info windows to refresh.

What you suggested about a `<info-window-group>` seems like a very elegant solution.
