### ISSUE TITLE
[Poll] API change proposition

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [GuillaumeLeclerc/vue-google-maps#51]
I have a (slightly breaking) API change to propose to the community. Please tell me what you think about it.

Instead of having Vue as a dependency (that leads to some problem with duplicate instance of Vue some times and two build for `vue-google-maps` (one for bundlers and the other for "normal" JavaScript). We might want to turn it into a Vue plugin. Here are the changes for users:

__before__
```javascript
//ES6
import {load} from `vue-google-maps`
load('token', ['places'])
//ES5
VueGoogleMaps.load('token', ['places'])
```

__after__
```javascript
//ES6
import Vue from 'vue'
import VueGoogleMaps from `vue-google-maps`
//ES5 + ES6 
Vue.use(VueGoogleMaps, {
  token: 'token',
  libraries: ['places']
})
```

On the other hand, I don't think there would be any changes in the the way we use components.

This way we could remove all dependencies of `vue-google-maps` and we would be sure there is no duplication of `vue`. We could also think about globally registered components.

What do you think ?

**Comment by dominikveils** [comment]
I think its a nice feature.
So you can make the MapObject accessible from Vue itself globally.

**Comment by GuillaumeLeclerc** [comment]
@dominikveils It's not possible to make the map available globally for a very simple reason. There is no limit on the number of maps on the page. We could make available an array of mapObjects though. 

I'm trying to make the library generic enough. If you need to access the map object that means I'm doing something wrong so feel free to make a new issue :) 

If you really want to access it you can already do it: 

```vue
<template>
  <map v-ref:map ></map>
</template>

<script>
  export default {
      created() {
        this.$refs.map.mapObject.then((m) => {console.log("the map has been loaded and is", m);})
      }
  }
```

**Comment by dominikveils** [comment]
@GuillaumeLeclerc thats nice, and what I need. So your changes will not break much.
I'd like to use map with the `Vue.use` instead of using `load` function.

**Comment by GuillaumeLeclerc** [comment]
Thank you for your feedback. I'll wait for some time and if nobody see it as a problem I'll do it in v1

**Comment by smartpierre** [comment]
:+1:

**Comment by hthabet** [comment]
:+1:

**Comment by juukie** [comment]
:+1:

**Comment by schmidex** [comment]
:+1:

**Comment by GuillaumeLeclerc** [comment]
Great news !

This small reorganization has dropped the build sizes to 45 and 64kb for the bundler and old school version respectively.

Thank you for your involvement. I will start another about the last decision I need to take before releasing v1.

Thanks !
