### ISSUE TITLE
PlaceInput template change

### ISSUE THREAD

**Issue by dominikveils** [GuillaumeLeclerc/vue-google-maps#52]
Hello,

Any way to change the PlaceInput template? The default one is not suitable for me, and I want to show it with my own template.

Thank You.

**Comment by GuillaumeLeclerc** [comment]
Of course you can do it. Just create new component that extends the original component with a new template.

**Comment by dominikveils** [comment]
Thank you for quick response. I'll try this.

**Comment by dominikveils** [comment]
Its working.
Just created new MyInput.vue with my template and used `Object.assign()` to extends the original PlaceInput. Its working and showing my template.
