### ISSUE TITLE
Marker and marker cluster ready

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [GuillaumeLeclerc/vue-google-maps#53]
@xkjyeah I have a question about your modifications in the loading process.

In marker you wait for the map to be ready but you also listen for the event that will tell if a marker is within a cluster. 

Does this event can be fired before the map load ? In this case marker set before the map is loaded will not be in the cluster.

Im I right ? Can we fix it if this is the case ?

**Comment by xkjyeah** [comment]
The register-marker event is fired from within deferredReady (I.e. the map
has already been loaded). When firing deferredMarker, the cluster replies.
at this point the cluster has finished loading. So there should be no
errors. Are you encountering problems?

**Comment by GuillaumeLeclerc** [comment]
No just wondering. Thank you for the answer.

I pushed a small fix for your DeferredPlugin. Can you check that I did not something bad ?
