### ISSUE TITLE
Place input 

### ISSUE THREAD

**Issue by efealatan** [GuillaumeLeclerc/vue-google-maps#62]
hello, 

thanks for these components! I have trouble with the place input when i try and pass a css class to it, the input box won't expand the width. 

do you have any suggestions ?

thanks

**Comment by GuillaumeLeclerc** [comment]
It should be working just fine. Do you have an example (fiddle where it breaks): Without code I will not be able to help you

**Comment by efealatan** [comment]
<place-input :place.sync="placeResult"  placeholder="Enter Address" :select-first-on-enter="true" :class="pure-input-1" >  </place-input>

I'm just passing the pure css class name to it.

thank you

**Comment by GuillaumeLeclerc** [comment]
I think I can see the problem from here.

`:class="pure-input-1"` means bind the property class to the value `pure-input-1`. Which is evaluated to the subtraction `pure - input - 1`. If you want the string "pure-input-1" you have two choices:

- `class="pure-input-1"` (see the missing colon)
- `:class="'pure-input-1'"` (see the single quote to tell vue : Its a string! )

Hope it helps
