### ISSUE TITLE
Missing VueGoogleMap when used standalone

### ISSUE THREAD

**Issue by JoshWillik** [GuillaumeLeclerc/vue-google-maps#64]
The documentation promises that a standalone include of `dist/vue-google-map.js` will create a global variable called `VueGoogleMap`.

It in fact only creates a global called `vueGoogleMapsInit`.

**Comment by xkjyeah** [comment]
Hi, I don't see the problem you described. See: https://jsfiddle.net/7325f5g9/

**Comment by JoshWillik** [comment]
Yeah, sorry to have wasted your time. I can't explain why this wasn't working for me yesterday. My best guess is that some of my code was preventing this library from fully loading?

Anyway, everything looks OK now. Thanks for your response!
