### ISSUE TITLE
With a lot of markers it is getting laggy

### ISSUE THREAD

**Issue by FWSimon** [GuillaumeLeclerc/vue-google-maps#68]
Hi,

Am I the only one who has problems with laggy map when i have like 150 markers?

**Comment by GuillaumeLeclerc** [comment]
I was able to have about 1000 markers and it was decent.

Do you often do operations on the markers ?

**Comment by FWSimon** [comment]
I have a input field and for every key the user write it trigger a function that does this

* filter all the markers 
* empty all the markers
* pushing new markers into the map


```javascript
        /**
         * Show searched parameters in dropdown list & zoom the map
         */
        showSearch: function () {

            let self = this;

            //Search markers list for centername, address, cid.
            let filteredMarkers = _.filter(self.markersStatic, function (centerValue) {

                //We lovercase both markers data and input from the user.
                // @return true or false.
                return centerValue.centerWebname.replace(',', '').toLowerCase().indexOf(self.searchKeyword.toLowerCase()) > -1;
            });

            self.$set('dropdownResults', filteredMarkers);

            //Empty dropdown results.
            if (!self.searchKeyword) {
                self.$set('dropdownResults', {});
            }

            self.$set('markers', []); //empty markers before pushing filteredmarkers in.

            //For each filtered marker we update the map with the new searched centers.
            _.each(filteredMarkers, function (markerData) {

                //Overwrite map icon.
                var openingDate = new Date(markerData.opening_date);
                var today = new Date();
                var mapIcon;

                //We set another icon for the marker.
                if (today < openingDate) {
                    mapIcon = self.newCenterIcon;
                } else {
                    mapIcon = self.centerIcon;
                }

                //Push new markers on the map.
                self.markers.push({
                    position: {
                        lat: parseFloat(markerData.position.lat),
                        lng: parseFloat(markerData.position.lng)
                    },
                    centerWebname: markerData.webname,
                    slug: markerData.slug,
                    icon: {url: mapIcon},
                    id: markerData.id, //Is used to grab the Opening hours data.
                    opened: false
                });

            });



        },
```

It seems like every time it empty all the markers, its "lagging" so when the user type it just stop the user from typing until it have removed all the markers.

**Comment by FWSimon** [comment]
Don't know if you can see it, but has I type, it is lagging, and I don't pause anytime when I write the search keyword

![test](https://cloud.githubusercontent.com/assets/14801013/15112726/5ea4b694-15f0-11e6-8672-a52e24faf652.gif)

**Comment by GuillaumeLeclerc** [comment]
Ok, I see now. We had the same problem.

The slowness does not come from vue-google-maps but from the DOM. Here you are creating/deleting hundreds of DOM elements. every time the user types the vue filter is triggered. then a new array with filtered elements. Then the old `<marker>` are removed from the dom. and new ones are created according the the filterered array.

The solution we used is not to use any filter but have a `v-show` that uses the content of the user input. So when a user type the only thing done is switching on and off markers. No DOM elements are created/deleted (this is what is slow)

I hope it helps

**Comment by FWSimon** [comment]
Ahh that makes sense! thanks a lot, will try that out @GuillaumeLeclerc

**Comment by SimonJ** [comment]
works, you can close this 👍

**Comment by FWSimon** [comment]
wrong account :D
