### ISSUE TITLE
Cluster icons not working

### ISSUE THREAD

**Issue by SimonJ** [GuillaumeLeclerc/vue-google-maps#69]
Today when I was trying to test my google map my cluster is not showing.

Am i the only one with that error?

![skaermbillede 2016-05-12 kl 09 08 04](https://cloud.githubusercontent.com/assets/183790/15206712/89075d28-1821-11e6-95a0-1d81b090492d.png)

**Comment by jvv** [comment]
You are not the only one, see the examples (eg: https://googlemaps.github.io/js-marker-clusterer/examples/simple_example.html) - has nothing to do with vue-google-maps though

**Comment by GuillaumeLeclerc** [comment]
It's not vue-google-maps related indeed. There is nothing we can really do right now I think.

**Comment by jvv** [comment]
> There is nothing we can really do right now I think.

You can add your own image path in the styles property. For an example see: https://github.com/googlemaps/js-marker-clusterer/issues/55 (comment from +matteopelucco )

**Comment by FWSimon** [comment]
How can i add my own cluster icons to vue-google-maps :)? if i have this object


```javascript
VueGoogleMap.loaded.then(function () {
            self.mapOptions = {
                mapTypeControl: true,
                mapTypeControlOptions: {
                    style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
                    position: google.maps.ControlPosition.TOP_LEFT
                },
                streetViewControl: true,
                streetViewControlOptions: {
                    position: google.maps.ControlPosition.TOP_RIGHT
                },
                zoomControl: true,
                zoomControlOptions: {
                    position: google.maps.ControlPosition.TOP_RIGHT
                }
            };
        });
```

**Comment by jvv** [comment]
In my Map vue file I added the following to the data object:

	cluster_styles : [
		 {
			url: '/img/cluster/m1.png',
			height: 53,
			width: 53,
			textColor: '#FFFFFF',
			textSize: 14
		}
	]

And added `:styles="cluster_styles"` to the `<cluster>`

**Comment by FWSimon** [comment]
ahh cool thanks, will try that @jvv

**Comment by ethanclevenger91** [comment]
If you want to fallback to the default ones, this will help:

```js
data() {
return {
      sizes: [53, 56, 66, 78, 90],
      imagePath:'https://googlemaps.github.io/js-marker-clusterer/images/m',
      imageExtension:'png'
}
}, 
computed: {
styles() {
var vm = this;
      return = map(vm.sizes, function(value, index, collection) {
        return {
          url: vm.imagePath + (index + 1) + '.' + vm.imageExtension,
          height: value,
          width: value
        };
      });
}
}

...
<cluster :styles="styles">
     ...
</cluster>
```

In fact, that wouldn't be a terrible fallback in this library.
