### ISSUE TITLE
Probleme au loading

### ISSUE THREAD

**Issue by smartpierre** [GuillaumeLeclerc/vue-google-maps#7]
Salut,

j'utilise ton composant et j'ai un soucis.

Il semble bien que lorsque je fais : 

    import {load, Map, Marker } from 'vue-google-maps'

Webpack importe le fichier ``index.js`` qui est donc le code deja compile. C'est problematique car j'aurais besoin que webpack importe les fichiers *.js et *.vue du repertoire /src afin que je puisse les modifier / les faire evoluer / les debugger et eventuellement te soumettre des PR.

J'ai essaye de compile ton src/ avec webpack, mais je n'arrive pas a passer cette erreur : 

![screenshot from 2016-01-19 12 46 44](https://cloud.githubusercontent.com/assets/8858750/12417766/bcb819e4-beaa-11e5-9a43-8c4938814c58.png)

Si tu peut m'aider ca serait sympa :)

**Comment by GuillaumeLeclerc** [comment]
Je pense que tu as un fichier de configuration webpack générique. Ce qui veut dire que tu dois avoir dans la configuration de Babel loader quelque-chose comme : `exclude: 'mode_modules'`. Ca veut dire que Babel ne va pas compiler vue-google-maps. 

Tu as deux options :

- soit tu enlève la ligne qui exclut mode_modules mais tu vas du coup tout recompiler tes autres dépendances. Si tu en as beaucoup c'est problématique.
- tu peux cloner vue-google-maps et le mettre autre part et importer directement les fichiers sources ils seront compilées par webpack. Su tu veux contribuer c'est mieux comme ça car tu peux directement commit ton code.

Si tu parles suffisamment bien anglais c'est mieux d'utiliser cette langue. D'autres personnes seraient sans doute intéressés

**Comment by smartpierre** [comment]
Je vais cloner a part et voir ce que ca donne, merci. 
J'ai parle en francais pour etre sur de me faire comprendre, mais je peut faire en anglais :)

**Comment by smartpierre** [comment]
Ah au fait, c'est tout bon ! Je vais essayer de contribuer...

**Comment by GuillaumeLeclerc** [comment]
Parfait je ferme alors. Ce n'est pas obligatoire de contribuer. Si il y a des feature qui manque tu peux toujours faire une demande. Si j'ai le temps je me pencherais dessus
