### ISSUE TITLE
Uncaught SyntaxError: Duplicate data property in object literal not allowed in strict mode 

### ISSUE THREAD

**Issue by restran** [GuillaumeLeclerc/vue-google-maps#72]
Hi, vue-google-maps raise error "SyntaxError Duplicate data property in object literal not allowed in strict mode", in older version of Chrome, IE and Firefox, such as Chrome 38, and IE 11. 

However, this problem is not appeared in latest version of Chrome and Firefox.

**Comment by GuillaumeLeclerc** [comment]
I think it should be fixed quickly. I'll try to do it as soon as I can.

**Comment by GuillaumeLeclerc** [comment]
A fix has been merged an published on NPM
