### ISSUE TITLE
Having trouble retrieving the Google Maps object

### ISSUE THREAD

**Issue by francisortega** [GuillaumeLeclerc/vue-google-maps#73]
Hi, as the title says, I'm having trouble with retrieving the Google Maps object. I have read the wiki and tried retrieving it using the loaded.then function. Here's how I do it. 

```
VueGoogleMap.load({key:'API_KEY',libraries: 'places'});
Vue.component('map', VueGoogleMap.Map);
Vue.component('marker', VueGoogleMap.Marker);
```

    var app = new Vue({
        el: '#element-id',
        data: {}
        ready: function() {
            var self = this;
            VueGoogleMap.loaded.then(function() {
                  /* Not too sure what to do here to get the google.maps.Map object */
                  console.log(vm.mapObject);
                  console.log(vm.map);
            });
        }});

So as you can see, console.log(vm.mapObject) inside the loaded.then function displays nothing. I also tried: 'this.mapObject', 'self.mapObject', and other variations instead.

Is there anything I'm missing to retrieve the object? That's how I understand the explanation in wiki. Thanks in advance.

**Comment by GuillaumeLeclerc** [comment]
can you try : `self.$deferredReadyDeferred.then(function() {....`

**Comment by francisortega** [comment]
I replaced VueGoogleMap.loaded.then with that but I get a console error saying 'Cannot read property then of undefined'. Sorry but I really don't understand how to get the map object.

Inside the loaded.then function, is there a keyword or other function to get the map object?

**Comment by GuillaumeLeclerc** [comment]
Ho I get it why it's not working.

What you initially typed does not make sense. `VueGoogleMap.loaded`, means the library is loaded. What you want is when a __map__ is loaded. And I don't see a single `<map>` object in your snippet. 

Can you give me your full code please ?

**Comment by francisortega** [comment]
Oh ok. Then I definitely misunderstood the wiki. Here's my small sample code of how I'm trying to do it. https://jsfiddle.net/c0yrxkvb/20/

**Comment by GuillaumeLeclerc** [comment]
I did it for you: https://jsfiddle.net/taqknhks/

But you should not need to wait for a load event. What are you trying to achieve. There is almost always a better way.

**Comment by francisortega** [comment]
Sorry I don't see any changes on the link you provided. Basically, I need the map object so I can get its current bounds whether I zoom in or out. I wanted to get all the markers in the map that are visible within those bounds.

**Comment by GuillaumeLeclerc** [comment]
you can get the bounds and zoom in real time: 

`<map :bounds.sync="your_data_attribute" :zoom.sync="your_zoom_in_data"></map>`

If you really need the mapObject (which mean you are going against the vue philosophy, then you don't need vue-google-maps at all, you can just use the google library): I updated the fiddle:

https://jsfiddle.net/u92xw99L/2/

**Comment by francisortega** [comment]
Okay now I understand! Thank you so much for the help and quick response. I will close this ticket.
