### ISSUE TITLE
Marker stays on the map

### ISSUE THREAD

**Issue by smartpierre** [GuillaumeLeclerc/vue-google-maps#8]
Hi !

i'm on the latest version and I have some issues with the markers : 

- I add some markers to an array
- I empty the markers array
- markers are still showing on the map

Here is a gist : 

https://gist.github.com/smartpierre/59d9bf44743c32d6f85f

First page : 

![screenshot from 2016-01-19 15 57 52](https://cloud.githubusercontent.com/assets/8858750/12422088/79b7b06c-bec5-11e5-848a-0dad9c296290.png)

Second page : 

![screenshot from 2016-01-19 15 58 02](https://cloud.githubusercontent.com/assets/8858750/12422099/7f2b09f4-bec5-11e5-8aa7-7e56b48188eb.png)

**Comment by smartpierre** [comment]
Is there a specific way to destroy a marker ?

**Comment by GuillaumeLeclerc** [comment]
Are you sure it is the latest ? Are you using vue-router ?

**Comment by smartpierre** [comment]
I just checked again, it is indeed the latest version.
I am also using vue-router, is it the problem ?

**Comment by GuillaumeLeclerc** [comment]
The destroyed hook is broken if you combine vue 1.x with vue-router. I put an issue this morning on vue-router repo this morning. You should say you are impacted it might get solved faster.

**Comment by GuillaumeLeclerc** [comment]
I took a look at your code and everything looks fine. If you clone the repo you should get the commit 05008a0 that fix this bug for marker but I did'nt released as it is a hotfix.

Just a side note 

```javascript
            'bounds': function() {
                this.fetchBounds();
                this.$emit('mapMoved');
            },
            'center': function() {
                this.$emit('mapMoved');
            },
            'zoom': function () {
                this.$emit('mapMoved');
            }
```

You don't need this `mapMoved` event. `g-bounds_changed` (or just watch `bounds`) because if the user moves the center then the bounds change and if the user zooms the bounds change.

**Comment by smartpierre** [comment]
That's true ! thanks :)
