### ISSUE TITLE
Extend InfoWindow to accept MaxWidth Option

### ISSUE THREAD

**Issue by dillonbailey** [GuillaumeLeclerc/vue-google-maps#87]
Hello,

Great your work on these components!

I am planning on getting hands on with the src to extend the InfoWindow component to allow it to accept a MaxWidth setting as documented here: https://developers.google.com/maps/documentation/javascript/infowindows but wanted to see if this has already been looked at previously first?

Cheers,
DB

**Comment by GuillaumeLeclerc** [comment]
No I have not took a look at it because it was not in the google maps version when I first implemented infoWindow. This can be added in literally 4 lines of JSON in the InfoWindow component. The props watcher should be working fine with this new property

**Comment by dillonbailey** [comment]
Thanks Guillaume,

I was just looking through the source code and realized this may actually already be implemented through the options object of the Info Window component and may not require updating.

Will test it out and potentially provide an example for the Wiki.

DB

**Comment by GuillaumeLeclerc** [comment]
You are right. It should be working with the options
