### ISSUE TITLE
InvalidValueError: setCenter: not a LatLng or LatLngLiteral: in property lat: not a number

### ISSUE THREAD

**Issue by Mdpproduction** [GuillaumeLeclerc/vue-google-maps#89]
Hi guys,
every times that i pass the object with lat and lng, i got this error

`InvalidValueError: setCenter: not a LatLng or LatLngLiteral: in property lat: not a number`

And i initializing the center object in this way:

```
let data = response.json()

this.center = { 
     lat: parseFloat(data.list[0].latitude), 
     lng: parseFloat(data.list[0].longitude)
}
```

What am i missing ? Any suggestions ?

**Comment by GuillaumeLeclerc** [comment]
your data is probably available only after the component starts. If not can you post an example ?

**Comment by Mdpproduction** [comment]
This is the api call that i made to fetch the data, and then i fill the data in order to working with map:

`
this.$http.get(api_url)
    .then((response) => {
                let data = response.json()

 		this.center = { 
  			lat: parseFloat(data.list[0].latitude), 
 			lng: parseFloat(data.list[0].longitude)
 		}
		
 		for (let i in data.list) {
			this.markers.push({
				position: {
					lat: parseFloat(data.list[i].latitude),
					lng: parseFloat(data.list[i].longitude)
				},
				content: data.list[i].label
			})
		}	
	}, (response) => {

	})
`

And then inside created i call this methods:

`
created() {
    this.fetchData()
}
`

And finally the map component:

`
<map
	class="search-map"
	:center.sync="center"
	:zoom.sync="9"
	:options.sync="options"
>
	<marker 
  		v-for="m in markers"
  		:position.sync="m.position"
  		:clickable.sync="true"
  		:draggable.sync="true"
  		@g-click="center=m.position"
	>
		<info-window :content="m.content" 
					 :position="m.position"
					 :opened.sync="false"
		></info-window>
	</marker>
</map>
`

And another problem is how to use fitBounds callback in order to display more than one markers inside the map. Maybe a full example about that, could be useful in the future. Thanks!

**Comment by GuillaumeLeclerc** [comment]
if you make an api call, it will be available after the component loads. so while the api call is pending the center is not a number, this why you get this error. If you put a default center you should not have this error

**Comment by Mdpproduction** [comment]
My bad. Sorry, I am still at the beginning with js. Thanks man!
