### ISSUE TITLE
Reading bounds of the map

### ISSUE THREAD

**Issue by jvv** [GuillaumeLeclerc/vue-google-maps#97]
I'm having trouble reading the bounds of the map. I've added bounds to the map element like this: `:bounds.sync="map.bounds"` 

I see the bounds changing in Vue Devtools when I move or zoom the map. But when I try to read the properties of the bounds ( eg: `map.bounds.south` ) I get `undefined`.

Bounds in Vue Devtools
<img width="256" alt="screen shot 2016-08-11 at 12 02 28" src="https://cloud.githubusercontent.com/assets/454216/17585358/85d0598e-5fbb-11e6-84b6-5e3e36a5dd48.png">

Bounds in console output of attribute
<img width="324" alt="screen shot 2016-08-11 at 12 03 12" src="https://cloud.githubusercontent.com/assets/454216/17585373/9e9b92d0-5fbb-11e6-90a7-db866d402654.png">

What am I missing? I'd like to load markers from my server based on the bounds the user sees.

**Comment by smartpierre** [comment]
This is how I retrieve bounds : 

`this.boundaries.SELat = this.map.bounds.getSouthWest().lat();
this.boundaries.SELng = this.map.bounds.getNorthEast().lng();
this.boundaries.NWLat = this.map.bounds.getNorthEast().lat();
this.boundaries.NWLng = this.map.bounds.getSouthWest().lng();`

**Comment by jvv** [comment]
Thanks, that did the trick @smartpierre
